[package]
name = "boa"
version = "0.1.0"
edition = "2024"

[lib]
name = "boa"
path = "src/lib.rs"

[[bin]]
name = "boa-cli"
path = "src/bin/cli.rs"

[dependencies]
sexp = "1.1.4"
dynasm = "2.0.0"
dynasmrt = "2.0.0"

[dev-dependencies]
prettydiff = "0.6.4"